### PR TITLE
Buying tokens from opensea directly from club page

### PR DESCRIPTION
**Pull request by mg6maciej**
Token and user addresses are hardcoded and requires styling.

### CODE REVIEW

**Comment by mg6maciej** [comment]
#105

**Comment by jakubsta** [comment]
Could be tested [here](https://cryptoverse-test.firebaseapp.com/)

**Comment by ghostbuster91** [comment]
image

It stays on this state forever after you reject transactions.

**Comment by ghostbuster91** [comment]
Most of the time I get this error:
```
Error: Unable to match offer with auction
    at e.<anonymous> (/static/js/2.2813b7a3.chunk.js:1)
    at r (/static/js/2.2813b7a3.chunk.js:1)
    at Object.next (/static/js/2.2813b7a3.chunk.js:1)
    at s (/static/js/2.2813b7a3.chunk.js:1)
```
I was able to see metamask window only once.

**Comment by OrdonTeam** [comment]
I wasn't able to see metamask window even once.
Once I got different error:
```
Error: Failed to validate buy order parameters: {"exchange":"0x7be8076f4ea4a4ad08075c2508e481d6c946d12b","maker":"0x157da080cb7f3e091eadfa32bc7430d9f142bee3","taker":"0x0000000000000000000000000000000000000000","makerRelayerFee":"250","takerRelayerFee":"0","makerProtocolFee":"0","takerProtocolFee":"0","feeMethod":1,"feeRecipient":"0x0000000000000000000000000000000000000000","side":0,"saleKind":0,"target":"0xf5b0a3efb8e8e4c201e2a935f110eaaf3ffecb8d","howToCall":0,"calldata":"0x23b872dd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000157da080cb7f3e091eadfa32bc7430d9f142bee30000000000000000000000000000000000000000000000000000000000001181","replacementPattern":"0x00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","staticTarget":"0x0000000000000000000000000000000000000000","staticExtradata":"0x","paymentToken":"0x0000000000000000000000000000000000000000","basePrice":"70000000000000000","extra":"0","listingTime":"1536655550","expirationTime":"0","salt":"68774319327818133701382120189167581410010662114136116656729343875787000026569","metadata":{"asset":{"id":"4481","address":"0xf5b0a3efb8e8e4c201e2a935f110eaaf3ffecb8d"},"schema":"ERC721"},"hash":"0xe1417a7dd4517bd3d2b70902babf4f1c307ba8709369198bb7e7f77c7ef87aff","v":27,"r":"0x3fcf2a2e4f5b9951ca130cdb299c214ed7712a08c1e45d0dc7c5b0b8ce207f2c","s":"0x409bf559d94224915a78fa6e344a3faa910f5256383164c83ffa114446838d3c"}
    at e.<anonymous> (seaport.js:1063)
    at r (seaport.js:40)
    at Object.next (seaport.js:21)
    at s (seaport.js:12)
```

**Pull request merged**
